"""
Sequence creation and future target alignment.

Builds temporal input sequences and aligns each sequence strictly with its
corresponding future target window:
    Input:  W_t ... W_{t + sequence_length - 1}
    Target: the ``forecast_horizon``-th same-host window whose start is strictly
            after the final input window's end.

Strict Anti-Leakage Constraints:
1. Sequences are created independently per host; no cross-host traffic mixing.
2. Horizon counts eligible, strictly future windows, not dataframe row offsets.
3. The target starts strictly after every input window ends, so overlapping
   sliding windows cannot be reused as future targets.
4. The current window is NEVER used as its own target.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import numpy as np
import pandas as pd

from ...config import AegisFlowConfig
from ...logging_setup import get_logger

log = get_logger("SEQUENCES")

# Standard numerical features extracted per window into model feature vectors
STANDARD_NUMERIC_WINDOW_FEATURES: tuple[str, ...] = (
    "flow_count",
    "packet_count_sum",
    "packet_count_mean",
    "byte_count_sum",
    "byte_count_mean",
    "duration_mean",
    "packets_per_second_mean",
    "bytes_per_second_mean",
    "bytes_per_packet_mean",
    "packet_size_mean",
    "packet_size_std_mean",
    "inter_arrival_mean",
    "syn_count_sum",
    "ack_count_sum",
    "rst_count_sum",
    "fin_count_sum",
    "psh_count_sum",
    "syn_ratio",
    "ack_ratio",
    "rst_ratio",
    "fin_ratio",
    "psh_ratio",
    "tcp_window_size_mean",
    "unique_destination_ips",
    "unique_destination_ports",
    "unique_source_ports",
    "destination_port_entropy",
    "connection_burst_max",
    "attack_flow_ratio",
    "benign_flow_ratio",
)


@dataclass
class SequenceConfig:
    sequence_length: int = 10
    forecast_horizon: int = 1
    stride: int = 1

    @classmethod
    def from_config(cls, cfg: AegisFlowConfig, **overrides: Any) -> SequenceConfig:
        w_cfg = cfg.config.windowing
        return cls(
            sequence_length=int(overrides.get("sequence_length") or w_cfg.sequence_length),
            forecast_horizon=int(overrides.get("forecast_horizon") or w_cfg.forecast_horizon),
            stride=int(overrides.get("stride") or 1),
        )


def build_host_sequences(
    windows_df: pd.DataFrame,
    cfg: AegisFlowConfig | None = None,
    *,
    sequence_length: int | None = None,
    forecast_horizon: int | None = None,
    stride: int = 1,
    feature_columns: list[str] | tuple[str, ...] | None = None,
) -> pd.DataFrame:
    """Build chronological temporal sequences and strictly future targets per host.

    Parameters:
        windows_df: Host windows generated by ``aggregate_host_windows``.
        cfg: Optional project configuration.
        sequence_length: Number of consecutive past windows forming model input (default 10).
        forecast_horizon: One-based count of eligible same-host windows with
            ``window_start > final_input_window.window_end`` (default 1).
        stride: Step stride between consecutive sequences for a host (default 1).
        feature_columns: Specific numeric columns to include in the feature vector.

    Returns:
        DataFrame containing sequences, future targets, and temporal bounds.
    """
    if windows_df.empty:
        log.warning("empty windows DataFrame passed to build_host_sequences")
        return pd.DataFrame()

    if cfg is not None:
        seq_cfg = SequenceConfig.from_config(
            cfg,
            sequence_length=sequence_length,
            forecast_horizon=forecast_horizon,
            stride=stride,
        )
    else:
        seq_cfg = SequenceConfig(
            sequence_length=int(sequence_length or 10),
            forecast_horizon=int(forecast_horizon or 1),
            stride=int(stride or 1),
        )

    L = seq_cfg.sequence_length
    H = seq_cfg.forecast_horizon
    step = seq_cfg.stride

    if L < 1:
        raise ValueError(f"sequence_length must be >= 1, got {L}")
    if H < 1:
        raise ValueError(f"forecast_horizon must be >= 1 (eligible future-window count), got {H}")

    # Determine numerical feature columns to extract
    if feature_columns is None:
        feat_cols = [c for c in STANDARD_NUMERIC_WINDOW_FEATURES if c in windows_df.columns]
    else:
        feat_cols = [c for c in feature_columns if c in windows_df.columns]

    if not feat_cols:
        raise ValueError("No valid numeric feature columns available to construct sequence features.")

    # Fill NA in feature columns with 0.0 for model readiness
    clean_df = windows_df.copy()
    clean_df[feat_cols] = clean_df[feat_cols].fillna(0.0)

    # Sort strictly by host and window_start
    clean_df = clean_df.sort_values(["host_id", "window_start"]).reset_index(drop=True)

    records: list[dict[str, Any]] = []

    # Process each host independently to guarantee zero cross-host leakage
    for host_id, host_group in clean_df.groupby("host_id", sort=False):
        n_windows = len(host_group)
        if n_windows < L + 1:
            # Not enough chronological windows for this host to form a sequence + future target
            continue

        host_group_sorted = host_group.sort_values("window_start").reset_index(drop=True)
        feat_matrix = host_group_sorted[feat_cols].to_numpy(dtype=np.float32)

        window_starts = host_group_sorted["window_start"].values
        window_ends = host_group_sorted["window_end"].values
        attack_presents = host_group_sorted["attack_present"].values
        dom_classes = host_group_sorted["dominant_class"].values
        dom_stages = host_group_sorted["dominant_stage"].values
        stage_dists = host_group_sorted["stage_distribution"].values
        confidences = host_group_sorted["label_confidence"].values

        parsed_starts = pd.to_datetime(window_starts)
        parsed_ends = pd.to_datetime(window_ends)
        if not parsed_starts.is_monotonic_increasing or not parsed_ends.is_monotonic_increasing:
            raise ValueError(f"Host windows are not chronological for host {host_id}")

        for i in range(0, n_windows - L + 1, step):
            in_slice = slice(i, i + L)
            final_input_idx = i + L - 1
            seq_end = pd.Timestamp(window_ends[final_input_idx])
            # Horizon is the one-based rank among windows whose start is strictly
            # after the final input end. With 60s windows/30s stride, horizon=1
            # skips the next overlapping windows and selects the first non-overlap.
            eligible = np.flatnonzero(parsed_starts[final_input_idx + 1:] > seq_end) + final_input_idx + 1
            if len(eligible) < H:
                continue
            target_idx = int(eligible[H - 1])
            input_ends = parsed_ends[in_slice]
            if pd.Timestamp(window_starts[target_idx]) <= input_ends.max():
                raise ValueError(f"Overlapping target window detected for host {host_id}")

            input_features = feat_matrix[in_slice].tolist()  # shape (L, len(feat_cols))
            target_features = feat_matrix[target_idx].tolist()  # shape (len(feat_cols),)

            seq_start = pd.Timestamp(window_starts[i])
            seq_end = pd.Timestamp(window_ends[final_input_idx])
            target_start = pd.Timestamp(window_starts[target_idx])
            target_end = pd.Timestamp(window_ends[target_idx])

            # Explicit strict no-overlap and future-order validation.
            if target_start <= seq_end:
                raise ValueError(
                    f"Temporal leakage detected: target_start ({target_start}) is not after "
                    f"sequence input window end ({seq_end}) for host {host_id}."
                )

            records.append({
                "sequence_id": f"{host_id}_seq_{i}",
                "host_id": str(host_id),
                "target_host_id": str(host_id),
                "seq_start_time": seq_start,
                "seq_end_time": seq_end,
                "target_window_start": target_start,
                "target_window_end": target_end,
                "forecast_horizon": H,
                "sequence_length": L,
                "sequence_features": input_features,
                "target_features": target_features,
                "target_attack_present": int(attack_presents[target_idx]),
                "target_dominant_class": str(dom_classes[target_idx]),
                "target_dominant_stage": str(dom_stages[target_idx]),
                "target_stage_distribution": str(stage_dists[target_idx]),
                "target_label_confidence": str(confidences[target_idx]),
                # Onset: attack target with no attack in ANY input window. Positives that are
                # not onsets are continuations of an attack already visible in the input.
                "target_is_onset": bool(attack_presents[target_idx]) and not bool(np.any(attack_presents[in_slice])),
            })

    seq_df = pd.DataFrame(records)
    if not seq_df.empty:
        seq_df = seq_df.sort_values(["seq_start_time", "host_id"]).reset_index(drop=True)

    log.info(
        "host sequences generated",
        total_sequences=len(seq_df),
        sequence_length=L,
        forecast_horizon=H,
        unique_hosts=seq_df["host_id"].nunique() if not seq_df.empty else 0,
        target_attack_sequences=int((seq_df["target_attack_present"] == 1).sum()) if not seq_df.empty else 0,
        target_benign_sequences=int((seq_df["target_attack_present"] == 0).sum()) if not seq_df.empty else 0,
    )
    return seq_df
